name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true # Fetches LFS objects, crucial if you use LFS for the models/parquet

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # IMPORTANT: Replace <your-username> and <your-space-name> below!
          git remote add huggingface https://oauth2:${HF_TOKEN}@huggingface.co/spaces/<ajeet9843>/<demand-and-inventory-optimization>
          git push --force huggingface main:main

